steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/rutgers-ultimate-website-$COMMIT_SHA-$BUILD_ID', '.' ]
    secretEnv:
      - NEXT_PUBLIC_API_KEY
      - NEXT_PUBLIC_AUTH_DOMAIN
      - NEXT_PUBLIC_PROJECT_ID
      - NEXT_PUBLIC_STORAGE_BUCKET
      - NEXT_PUBLIC_MESSAGING_SENDER_ID
      - NEXT_PUBLIC_APP_ID
      - NEXT_PUBLIC_MEASUREMENT_ID
      - NEXT_PUBLIC_GOOGLE_CLIENT_ID
      - STRIPE_SECRET_KEY
      - NEXT_PUBLIC_STRIPE_PUBLIC_KEY
      - FIREBASE_CLIENT_EMAIL
      - FIREBASE_PRIVATE_KEY
      - EASYPOST_API_KEY
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'gcr.io/$PROJECT_ID/rutgers-ultimate-website-$COMMIT_SHA-$BUILD_ID' ]
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: [ 'run', 'deploy', 'rutgers-ultimate-website', '--image', 'gcr.io/$PROJECT_ID/rutgers-ultimate-website-$COMMIT_SHA-$BUILD_ID', '--region', 'us-east4' ]
images:
  - gcr.io/$PROJECT_ID/rutgers-ultimate-website-$COMMIT_SHA-$BUILD_ID
availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/FIREBASE_PRIVATE_KEY/versions/1
      env: 'FIREBASE_PRIVATE_KEY'
    - versionName: projects/$PROJECT_ID/secrets/EASYPOST_API_KEY_test/versions/1
      env: 'EASYPOST_API_KEY'
    - versionName: projects/$PROJECT_ID/secrets/STRIPE_SECRET_KEY_test/versions/1
      env: 'STRIPE_SECRET_KEY'
    - versionName: projects/$PROJECT_ID/secrets/NEXT_PUBLIC_API_KEY/versions/1
      env: 'NEXT_PUBLIC_API_KEY'
    - versionName: projects/$PROJECT_ID/secrets/NEXT_PUBLIC_AUTH_DOMAIN/versions/1
      env: 'NEXT_PUBLIC_AUTH_DOMAIN'
    - versionName: projects/$PROJECT_ID/secrets/NEXT_PUBLIC_PROJECT_ID/versions/1
      env: 'NEXT_PUBLIC_PROJECT_ID'
    - versionName: projects/$PROJECT_ID/secrets/NEXT_PUBLIC_STORAGE_BUCKET/versions/1
      env: 'NEXT_PUBLIC_STORAGE_BUCKET'
    - versionName: projects/$PROJECT_ID/secrets/NEXT_PUBLIC_MESSAGING_SENDER_ID/versions/1
      env: 'NEXT_PUBLIC_MESSAGING_SENDER_ID'
    - versionName: projects/$PROJECT_ID/secrets/NEXT_PUBLIC_APP_ID/versions/1
      env: 'NEXT_PUBLIC_APP_ID'
    - versionName: projects/$PROJECT_ID/secrets/NEXT_PUBLIC_MEASUREMENT_ID/versions/1
      env: 'NEXT_PUBLIC_MEASUREMENT_ID'
    - versionName: projects/$PROJECT_ID/secrets/NEXT_PUBLIC_STRIPE_PUBLIC_KEY/versions/1
      env: 'NEXT_PUBLIC_STRIPE_PUBLIC_KEY'
    - versionName: projects/$PROJECT_ID/secrets/FIREBASE_CLIENT_EMAIL/versions/1
      env: 'FIREBASE_CLIENT_EMAIL'
