steps:
  # Fetch env file from secret manager
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: 'bash'
    args: [ '-c', "gcloud secrets versions access latest --secret=BUILD_ENV_FILE --format='get(payload.data)' | tr '_-' '/+' | base64 -d > secret_env_file" ]
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/rutgers-ultimate-website-$COMMIT_SHA-$BUILD_ID', '--secret', 'id=env_file,src=secret_env_file,target=/.env','.' ]
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'gcr.io/$PROJECT_ID/rutgers-ultimate-website-$COMMIT_SHA-$BUILD_ID' ]
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: [ 'run', 'deploy', 'rutgers-ultimate-website', '--image', 'gcr.io/$PROJECT_ID/rutgers-ultimate-website-$COMMIT_SHA-$BUILD_ID', '--region', 'us-east4' ]
images:
  - gcr.io/$PROJECT_ID/rutgers-ultimate-website-$COMMIT_SHA-$BUILD_ID
availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_NUMBER/secrets/FIREBASE_PRIVATE_KEY/versions/1
      env: 'FIREBASE_PRIVATE_KEY'
    - versionName: projects/$PROJECT_NUMBER/secrets/EASYPOST_API_KEY_test/versions/1
      env: 'EASYPOST_API_KEY'
    - versionName: projects/$PROJECT_NUMBER/secrets/STRIPE_SECRET_KEY_test/versions/1
      env: 'STRIPE_SECRET_KEY'
    - versionName: projects/$PROJECT_NUMBER/secrets/NEXT_PUBLIC_API_KEY/versions/1
      env: 'NEXT_PUBLIC_API_KEY'
    - versionName: projects/$PROJECT_NUMBER/secrets/NEXT_PUBLIC_AUTH_DOMAIN/versions/1
      env: 'NEXT_PUBLIC_AUTH_DOMAIN'
    - versionName: projects/$PROJECT_NUMBER/secrets/NEXT_PUBLIC_PROJECT_ID/versions/1
      env: 'NEXT_PUBLIC_PROJECT_ID'
    - versionName: projects/$PROJECT_NUMBER/secrets/NEXT_PUBLIC_STORAGE_BUCKET/versions/1
      env: 'NEXT_PUBLIC_STORAGE_BUCKET'
    - versionName: projects/$PROJECT_NUMBER/secrets/NEXT_PUBLIC_MESSAGING_SENDER_ID/versions/1
      env: 'NEXT_PUBLIC_MESSAGING_SENDER_ID'
    - versionName: projects/$PROJECT_NUMBER/secrets/NEXT_PUBLIC_APP_ID/versions/1
      env: 'NEXT_PUBLIC_APP_ID'
    - versionName: projects/$PROJECT_NUMBER/secrets/NEXT_PUBLIC_GOOGLE_CLIENT_ID/versions/1
      env: 'NEXT_PUBLIC_GOOGLE_CLIENT_ID'
    - versionName: projects/$PROJECT_NUMBER/secrets/NEXT_PUBLIC_MEASUREMENT_ID/versions/1
      env: 'NEXT_PUBLIC_MEASUREMENT_ID'
    - versionName: projects/$PROJECT_NUMBER/secrets/NEXT_PUBLIC_STRIPE_PUBLIC_KEY/versions/1
      env: 'NEXT_PUBLIC_STRIPE_PUBLIC_KEY'
    - versionName: projects/$PROJECT_NUMBER/secrets/FIREBASE_CLIENT_EMAIL/versions/1
      env: 'FIREBASE_CLIENT_EMAIL'
